#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -o xtrace

python manage.py migrate --no-input
python manage.py initadmin
if [ "${DEBUG}" == "True" ]; then
  python manage.py runserver 0.0.0.0:8001
else
   python manage.py collectstatic --no-input
   gunicorn shadowmere.wsgi:application --bind 0.0.0.0:8001 -k gevent -w 6 --capture-output
fi
