# Generated by Django 4.0.3 on 2022-03-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxylist', '0003_alter_proxy_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='times_check_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proxy',
            name='times_checked',
            field=models.IntegerField(default=0),
        ),
    ]
