# Generated by Django 4.0.3 on 2022-04-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxylist', '0005_remove_proxy_times_check_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='times_check_succeeded',
            field=models.IntegerField(default=0),
        ),
    ]
