# Generated by Django 4.0.3 on 2022-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxylist', '0006_proxy_times_check_succeeded'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='ip_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proxy',
            name='location_country_code',
            field=models.CharField(default='', max_length=3),
        ),
    ]
