# Generated by Django 4.1.1 on 2022-09-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxylist", "0008_proxy_location_country_alter_proxy_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxy",
            name="port",
            field=models.IntegerField(default=0),
        ),
    ]
