# Generated by Django 4.1.7 on 2023-03-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxylist', '0010_subscription_alter_proxy_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='kind',
            field=models.CharField(choices=[('PLAIN', 'plain'), ('BASE64', 'base64')], default='PLAIN', max_length=10),
        ),
    ]
