# Generated by Django 5.0.3 on 2024-04-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxylist", "0015_alter_tasklog_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="finish_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
