# Generated by Django 5.0.3 on 2024-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxylist", "0016_alter_tasklog_finish_time_alter_tasklog_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="details",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
