# Generated by Django 5.2.7 on 2025-10-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxylist", "0018_delete_tasklog"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackListHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=1024, unique=True)),
            ],
        ),
    ]
