# Generated by Django 6.0.3 on 2026-03-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxylist", "0019_blacklisthost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxy",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="proxy",
            name="location_country_code",
            field=models.CharField(db_index=True, default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="proxy",
            name="port",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
