# Generated by Django 5.2.13 on 2026-08-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxylist", "0020_add_indexes_for_filtered_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="proxy",
            index=models.Index(
                fields=["is_active", "location_country_code"],
                name="proxylist_p_is_acti_f6429c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proxy",
            index=models.Index(
                fields=["is_active", "port"], name="proxylist_p_is_acti_3ee00a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proxy",
            index=models.Index(
                fields=["is_active", "last_active"],
                name="proxylist_p_is_acti_c56ce3_idx",
            ),
        ),
    ]
