# Generated by Django 3.2.8 on 2021-11-22 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("proxylist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxy",
            name="last_active",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
