# Generated by Django 4.0.4 on 2022-06-06 12:09

from django.db import migrations, models
from utils import validators


class Migration(migrations.Migration):
    dependencies = [
        ("proxylist", "0007_proxy_ip_address_proxy_location_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxy",
            name="location_country",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="proxy",
            name="url",
            field=models.CharField(
                max_length=1024,
                unique=True,
                validators=[
                    validators.validate_sip002,
                    validators.validate_proxy_can_connect,
                ],
            ),
        ),
    ]
