# Generated by Django 4.2.5 on 2023-09-17 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("proxylist", "0012_subscription_alive_subscription_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="alive_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="subscription",
            name="error_message",
            field=models.CharField(default="", max_length=10000),
        ),
    ]
