# Generated by Django 5.0.3 on 2024-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxylist", "0013_subscription_alive_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("finish_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
