# Generated by Django 5.0.6 on 2024-06-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxylist', '0017_tasklog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='ip_address',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='location_country',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='location_country_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='port',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
